
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Wed Feb 10 01:29:20 CET 2021
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CONST = 6;
  public static final int EQUALS = 19;
  public static final int R_ROUND_BR = 45;
  public static final int NUMCONST = 46;
  public static final int CASE = 18;
  public static final int SEMI = 40;
  public static final int GREATER = 21;
  public static final int CONTINUE = 17;
  public static final int LESS = 23;
  public static final int MINUS = 27;
  public static final int AND = 34;
  public static final int OR = 33;
  public static final int COMMA = 41;
  public static final int CLASS = 4;
  public static final int INC = 31;
  public static final int DIV = 29;
  public static final int QUESTION_MARK = 35;
  public static final int PLUS = 26;
  public static final int GREATER_EQUALS = 22;
  public static final int IF = 7;
  public static final int DOT = 36;
  public static final int R_SQUARE_BR = 43;
  public static final int EOF = 0;
  public static final int RETURN = 14;
  public static final int EQUAL = 25;
  public static final int NEW = 11;
  public static final int error = 1;
  public static final int PROGRAM = 2;
  public static final int MUL = 28;
  public static final int MOD = 30;
  public static final int R_CURRLY_BR = 39;
  public static final int IDENT = 47;
  public static final int BREAK = 3;
  public static final int VOID = 16;
  public static final int SWITCH = 8;
  public static final int COLON = 37;
  public static final int ELSE = 5;
  public static final int LESS_EQUALS = 24;
  public static final int READ = 13;
  public static final int CHARCONST = 49;
  public static final int WHILE = 10;
  public static final int NOT_EQUALS = 20;
  public static final int BOOLCONST = 48;
  public static final int EXTENDS = 15;
  public static final int L_SQUARE_BR = 42;
  public static final int L_ROUND_BR = 44;
  public static final int DEC = 32;
  public static final int L_CURRLY_BR = 38;
  public static final int PRINT = 12;
  public static final int DO = 9;
}

